config/routes.rb
Rails.application.routes.draw do

  get 'urls/catalog'

  namespace :admin do
       resources :author
       resources :publishers
       resources :books
  end
 
  scope :module => "admin" do
    resources :books
  end
  resources :catalog

  root :to => 'catalog#index'
  match 'catalog/latest', :to => 'catalog#latest', via: [:get, :post]
  get 'about/index'

end

app/models/book.rb
class Book < ActiveRecord::Base
	has_and_belongs_to_many :authors
  belongs_to :publisher

  #mount_uploader :image, ImageUploader

	has_attached_file :cover_image,
   		:styles => { :medium => "300x300>", :thumb => "100x100>" },
      :default_style => :medium,
   		:default_url => "/images/:style/missing.png"
  	validates_attachment_content_type :cover_image,
   		:content_type => /\Aimage\/.*\Z/

  	validates_length_of :title, :in => 1..255
  	validates :publisher, :presence => true
  	validates :authors, :presence => true
  	validates :published_at, :presence => true
  	validates_numericality_of :page_count, :only_integer => true
  	validates_numericality_of :price
  	#validates_format_of :isbn, :with => /[0-9\-xX]{13}/
  	validates_uniqueness_of :isbn

  	attr_protected
	
# roughly speaking sets list of model protected attributes to [] # making all attributes accessible while mass-assignment attr_protected
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @page_title = 'Listing books'
    sort_by = params[:sort_by]
    @books = Book.paginate(:page => params[:page], :per_page => 10).order(sort_by)
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @book = Book.find(params[:id])
    @page_title = "#{@book.title}"
    respond_to do |format| format.html # show.html.erb
       format.json { render json: @book }
    end
  end

  # GET /books/new
  def new
    load_data
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
    load_data
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :publisher_id, :published_at, :isbn,
     :blurb, :price, :created_at, :updated_at, :cover_image,
     :page_count, {:author_ids => []})
  end

  def load_data
    @authors = Author.all
    @publishers = Publisher.all
  end
  # POST /books
  # POST /books.json
  def create
    @book = Book.new(params[:book])
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.'}
        format.json { render action: 'show', status: :created, location: @book }
      else
        load_data
        format.html { render action: 'new' }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end 
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :publisher_id, :published_at, :isbn, :blurb, :price, :created_at, :updated_at)
    end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/views/admin/books/_form.html.erb
<%= error_messages_for 'book' %>
<p><label for="book_title">Title</label><br/>
<%= text_field 'book', 'title' %></p>
<p><label for="book_publisher">Publisher</label><br/>
<%= collection_select :book, :publisher_id, @publishers, :id, :name %></p>
<p><label for="book[author_ids][]">Authors</label><br/>
<%= select_tag 'book[author_ids][]',
     options_from_collection_for_select(@authors, :id, :name,
@book.authors.collect{|author| author.id}),
{ :multiple => true, :size => 5 } %> </p>
<p><label for="book_published_at">Published at</label><br/>
<%= datetime_select 'book', 'published_at' %></p>
<p><label for="book_isbn">Isbn</label><br/>
<%= text_field 'book', 'isbn' %></p>
<p><label for="book_blurb">Blurb</label><br/>
<%= text_area 'book', 'blurb' %></p>
<p><label for="book_price">Price</label><br/>
<%= text_field 'book', 'price' %></p>
<p><label for="book_page_count">Page count</label><br/>
<%= text_field 'book', 'page_count' %></p>
<p><label for="book_cover_image">Cover image</label><br/>
<%= file_field 'book', "cover_image" %></p>

app/views/admin/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form' %>
  <%= submit_tag 'Create' %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/admin/books/index.html.erb
<table> <tr>
   <th><a href="?sort_by=publisher_id">Publisher</a></th>
   <th><a href="?sort_by=title">Title</a></th>
   <th><a href="?sort_by=isbn">ISBN</a></th>
   <th colspan="3"></th>
</tr>
  <% for book in @books %>
   <tr>
     <td><%=h book.publisher.name %></td>
     <td><%=h book.title %></td>
     <td><%=h book.isbn %></td>
     <td><%= link_to 'Show', :action => 'show', :id => book %></td>
     <td><%= link_to 'Edit', :action => 'edit', :id => book %></td>
     <td><%= link_to 'Destroy', book, :confirm => 'Are you sure?',
      :method => :delete %></td>
   </tr>
  <% end %>
</table>
<%= will_paginate @books %>
<br />
<%= link_to 'New book', :action => 'new' %>

app/views/admin/books/new.html.erb
<h1>New book</h1>
<%= form_tag( {:action => 'create'}, :multipart => true ) do %>
  <%= render :partial => 'form' %>
  <%= submit_tag 'Create' %>
<% end %>
<%= link_to 'Back', :action => 'index' %>

app/views/admin/books/show.html.erb
<dl>
  <dt>Title</dt>
  <dd><%= @book.title %></dd>
  <dt>Publisher</dt>
  <dd><%= @book.publisher.name %></dd>
  <dt>Published at</dt>
  <dd><%= @book.published_at.strftime("%m/%d/%Y at %I:%M%p") %></dd>
  <dt>Authors</dt>
  <dd><%= @book.authors.collect{|author| author.name }.join(', ') %></dd>
  <dt>ISBN</dt>
  <dd><%= @book.isbn %></dd>
  <dt>Blurb</dt>
  <dd><%= @book.blurb %></dd>
  <dt>Price</dt>
  <dd><%= @book.price %></dd>
  <dt>Page count</dt>
  <dd><%= @book.page_count %></dd>
  <dt>Cover image</dt>
  <%= @book.cover_image %>
   <dd> <%= image_tag @book.cover_image.url %></dd>
</dl>
<p><%= link_to "Edit", :action => "edit", :id => @book %> |
<%= link_to "Back", :action => "index" %></p>