config/routes.rb
Rails.application.routes.draw do

  get 'urls/catalog'

  namespace :admin do
       resources :author
       resources :publishers
       resources :books
  end
 
  scope :module => "admin" do
    resources :books
  end
  resources :catalog

  root :to => 'catalog#index'
  match 'catalog/latest', :to => 'catalog#latest', via: [:get, :post]
  get 'about/index'

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
	has_many :books
	validates_length_of :name, :in => 2..255
  	validates_uniqueness_of :name
  	attr_accessible :name
end

app/controllers/admin/publishers_controller.rb
class Admin::PublishersController < ApplicationController
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
    @publisher = Publisher.find(params[:id])
    @page_title = @publisher.name
    respond_to do |format|
      format.html # show.html.erb format.json { render json: @publisher }
    end
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(params[:publisher])
    respond_to do |format|
      if @publisher.save
       format.html { redirect_to([:admin, @publisher],
  :notice => 'Publisher was successfully created.') }
       format.json { render json: @publisher, status: :created,
  location: @publisher }
      else
       format.html { render :action => "new" }
       format.json { render json: @publisher.errors,
  status: :unprocessable_entity }
      end 
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    @publisher = Publisher.find(params[:id])
    respond_to do |format|
     if @publisher.update_attributes(params[:publisher])
       format.html { redirect_to([:admin, @publisher],
      :notice => 'Publisher was successfully updated.') }
         format.json { head :no_content }
      else
       format.html { render :action => "edit" }
       format.json { render json: @publisher.errors,
      :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher = Publisher.find(params[:id])
    @publisher.destroy
    respond_to do |format|
     format.html { redirect_to(admin_publishers_url) }
     format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:name)
    end
end

app/helpers/admin/publishers_helper.rb
module Admin::PublishersHelper
end

app/views/admin/publishers/_form.html.erb
<%= form_for([:admin, @publisher]) do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
      <% @publisher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/publishers/edit.html.erb
<h1>Editing Publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', :action => 'show', :id => @publisher %> |
<%= link_to 'Back', admin_publishers_path %>

app/views/admin/publishers/index.html.erb
<h1>Listing publishers</h1>
<table>
  <tr>
   <th>Name</th>
<th></th>
     <th></th>
   <th></th>
  </tr>
<% @publishers.each do |publisher| %>
  <tr>
   <td><%= publisher.name %></td>
   <td><%= link_to 'Show', :action => 'show', :id => publisher %></td>
   <td><%= link_to 'Edit', :action => 'edit', :id => publisher %></td>
   <td><%= button_to 'Destroy', {:action => 'destroy', :id => publisher},
{:method => :delete, :confirm => 'Are you sure?'} %></td>
  </tr>
<% end %>
</table>
<br />
<%= link_to 'New Publisher', :action => 'new' %>

app/views/admin/publishers/new.html.erb
<h1>New Publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_publishers_path %>

app/views/admin/publishers/show.html.erb
<dl>
  <dt>Name</dt>
  <dd><%= @publisher.name %></dd>
</dl>
<%= link_to 'Edit', :action => 'edit', :id => @publisher %> |
<%= link_to 'Back', admin_publishers_path %>